### ISSUE TITLE
circleci node version is wrong

### ISSUE THREAD

**Issue by JRJurman** [bbesmanoff/indoor-umbrellas#16]
currently the file lists the node version as 0.12.0
this should be updated to 4.1.0

![image](https://cloud.githubusercontent.com/assets/326557/10240442/fcf9cfe0-68a9-11e5-9475-79ae77f61667.png)

**Comment by bbesmanoff** [comment]
At the time of development, Node 4.1.0 wasn't a [default node version](https://circleci.com/docs/environment#node-js)
