### ISSUE TITLE
Home Page / Facebook Feed

### ISSUE THREAD

**Issue by bbesmanoff** [bbesmanoff/indoor-umbrellas#5]
Facebook feed for the home page

**Comment by dani5447** [comment]
Includes retrieving friends' statuses and updating user status. 

Code for doing a status update is (where hello world is the message) :
FB.login(function(){
  // Note: The call will only work if you accept the permission request
  FB.api('/me/feed', 'post', {message: 'Hello, world!'});
}, {scope: 'publish_actions'});

https://developers.facebook.com/docs/javascript/examples

**Comment by dani5447** [comment]
relevant links:
https://developers.facebook.com/docs/graph-api/reference/v2.0/user/feed
for news feed > https://developers.facebook.com/docs/graph-api/reference/v2.0/user/home
http://stackoverflow.com/questions/27473562/get-news-feed-using-facebook-graph-api
https://illuminatikarate.com/blog/facebook-graph-api-requires-access-token-for-feed-access/
