### ISSUE TITLE
Home Page / Stock Ticker

### ISSUE THREAD

**Issue by bbesmanoff** [bbesmanoff/indoor-umbrellas#6]
Display the top 5 stocks for the current user

**Comment by mschug** [comment]
Since there isn't a database yet, we can start with a ticker search. Once that's working the Top 5 Stocks can be faked until there are working accounts (use price or market cap instead of what a user has bought).

**Comment by mschug** [comment]
The React component for these things is done apart from potential style edits. The prices aren't pulled from the API yet, and can most likely be implemented at the same time as the more substantial Stocks page.
